// functions/sitemap.xml.js
//
// WHY THIS EXISTS
// public/_redirects proxies /sitemap.xml to the Supabase sitemap function with a
// 200 rewrite. Cloudflare Pages does not proxy _redirects rules to another
// origin, so /sitemap.xml has been returning the SPA shell as text/html: 1,013
// URLs that crawlers could not read, and a sitemap that looked like a homepage.
// This function fetches the same source and returns it as XML.
//
// It also guarantees /about is listed. The About page is the entity page the AI
// search work depends on, and it is generated by functions/about.js rather than
// by the database the sitemap is built from, so nothing else would add it.

const SOURCE = 'https://kumfuludrhoqirxvaqja.supabase.co/functions/v1/sitemap'
const SITE = 'https://mcmullenresidential.com'
const ABOUT = `${SITE}/about`

export async function onRequest() {
  let xml = ''
  try {
    const res = await fetch(SOURCE, { cf: { cacheTtl: 300 } })
    if (res.ok) xml = await res.text()
  } catch {
    xml = ''
  }

  // Source unreachable: still answer with a valid sitemap carrying the pages
  // that are generated here, rather than a 500 or an HTML shell.
  if (!xml.includes('<urlset')) {
    xml =
      '<?xml version="1.0" encoding="UTF-8"?>\n' +
      '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' +
      `  <url><loc>${SITE}/</loc></url>\n` +
      `  <url><loc>${ABOUT}</loc><priority>0.9</priority></url>\n` +
      '</urlset>\n'
  } else if (!xml.includes(ABOUT)) {
    xml = xml.replace(
      '</urlset>',
      `  <url><loc>${ABOUT}</loc><changefreq>monthly</changefreq><priority>0.9</priority></url>\n</urlset>`
    )
  }

  return new Response(xml, {
    headers: {
      'content-type': 'application/xml; charset=utf-8',
      'cache-control': 'public, max-age=900, s-maxage=3600',
    },
  })
}
