-- Phase 1 of campaign-aware tracking infrastructure
-- Adds campaign_slug/campaign_name to email_blasts, plus a fine-grained email_events
-- table for opens / clicks / bounces. Powers the redesigned admin dashboard.

ALTER TABLE public.email_blasts
  ADD COLUMN IF NOT EXISTS campaign_slug TEXT,
  ADD COLUMN IF NOT EXISTS campaign_name TEXT;

-- Backfill the prior Union House blast so it shows up as a named campaign
UPDATE public.email_blasts
SET campaign_slug = 'union-house-coming-soon',
    campaign_name = 'Union House #5C — Off-Market Launch'
WHERE listing_slug = '1515-union-st-coming-soon'
  AND campaign_slug IS NULL;

-- Fine-grained event log for every single email sent
CREATE TABLE IF NOT EXISTS public.email_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  blast_id uuid REFERENCES public.email_blasts(id) ON DELETE SET NULL,
  campaign_slug TEXT,
  recipient_email TEXT NOT NULL,
  recipient_metadata jsonb DEFAULT '{}'::jsonb,
  resend_email_id TEXT,
  event_type TEXT NOT NULL CHECK (event_type IN ('queued','sent','delivered','bounced','opened','clicked','complained','unsubscribed')),
  url_clicked TEXT,
  user_agent TEXT,
  ip_address TEXT,
  occurred_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.email_events IS 'One row per email event. Generated by the tracking worker (pixel + click redirect) and Resend webhooks. Powers per-campaign open/click metrics.';

CREATE INDEX IF NOT EXISTS idx_email_events_blast      ON public.email_events (blast_id);
CREATE INDEX IF NOT EXISTS idx_email_events_campaign   ON public.email_events (campaign_slug, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_email_events_recipient  ON public.email_events (recipient_email, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_email_events_type       ON public.email_events (event_type, occurred_at DESC);

ALTER TABLE public.email_events ENABLE ROW LEVEL SECURITY;

-- Lightweight pageviews table for self-produced analytics (Phase 2 — see analytics plan)
CREATE TABLE IF NOT EXISTS public.pageviews (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  page_path TEXT NOT NULL,
  referrer TEXT,
  campaign_slug TEXT,
  user_agent TEXT,
  ip_hash TEXT,
  session_id TEXT,
  metadata jsonb DEFAULT '{}'::jsonb,
  occurred_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_pageviews_path     ON public.pageviews (page_path, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_pageviews_campaign ON public.pageviews (campaign_slug, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_pageviews_session  ON public.pageviews (session_id);

ALTER TABLE public.pageviews ENABLE ROW LEVEL SECURITY;

-- Tag the leads table too so investor-campaign signups can be filtered by campaign
ALTER TABLE public.leads
  ADD COLUMN IF NOT EXISTS campaign_slug TEXT;

CREATE INDEX IF NOT EXISTS idx_leads_campaign ON public.leads (campaign_slug);