// Public share-link helper. Mints (or reuses) a document_shares row for any
// shareable entity and returns the public /share/:token URL. Generic over
// entity kind so the same Share button works for CMAs now and Net Sheets /
// other docs later — add a new ShareEntityKind + handle it in get_shared.

import { supabase } from '@/lib/supabase'

export type ShareEntityKind = 'cma' | 'net_sheet'

export function shareUrlFromToken(token: string): string {
  return `${window.location.origin}/share/${token}`
}

// Returns the public URL for an active share link for the entity, reusing an
// existing (non-revoked, non-expired) link if one exists, otherwise creating one.
export async function getOrCreateShareLink(params: {
  entityKind: ShareEntityKind
  entityId: string
  tenantId: string
  clientId?: string | null
  createdBy?: string | null
}): Promise<string> {
  const { entityKind, entityId, tenantId, clientId = null, createdBy = null } = params

  // Reuse an existing active share if present.
  const { data: existing } = await supabase
    .from('document_shares')
    .select('token, expires_at, revoked_at')
    .eq('tenant_id', tenantId)
    .eq('entity_kind', entityKind)
    .eq('entity_id', entityId)
    .is('revoked_at', null)
    .order('created_at', { ascending: false })
    .limit(1)
    .maybeSingle()

  if (
    existing?.token &&
    (!existing.expires_at || new Date(existing.expires_at) > new Date())
  ) {
    return shareUrlFromToken(existing.token)
  }

  // Otherwise mint a new one (token is generated by the DB default).
  const { data, error } = await supabase
    .from('document_shares')
    .insert({
      tenant_id: tenantId,
      entity_kind: entityKind,
      entity_id: entityId,
      client_id: clientId,
      created_by: createdBy,
    })
    .select('token')
    .single()

  if (error || !data?.token) {
    throw new Error(error?.message || 'Could not create share link')
  }
  return shareUrlFromToken(data.token)
}
